[package]
name = "agave-block-production-scheduler"
description = "Agave block production scheduler"
documentation = "https://docs.rs/agave-block-production-scheduler"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
agave-unstable-api = []

[lints]
workspace = true
