[package]
name = "agave-block-verification-stage"
description = "Agave block verification stage"
documentation = "https://docs.rs/agave-block-verification-stage"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
agave-unstable-api = []

[dependencies]

[lints]
workspace = true
