[workspace]

[package]
name = "bank-event-consumer"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
flatrecord = "0.1.0"
serde_json = { version = "1", features = ["preserve_order"] }
shaq = { git = "https://github.com/anza-xyz/shaq", rev = "c7144f800409089cf2029367fd1fc32dcbebdc71" }
signal-hook = "0.4"
wincode = { version = "0.5.5", features = ["derive"] }
